#pragma once

#include QMK_KEYBOARD_H

enum MyLayers{
_LAYER_BASE = 0,
_LAYER_SYM ,
_LAYER_NUM ,
_LAYER_FUNC,
_LAYER_MOUSE,
_LAYER_COLEMAK,
_LAYER_CUSTOM_LAYOUT,
_LAYER_REVERSE_NUM,
_LAYER_REVERSE_BASE,
}

#define _LAYER_BASE_LEFT 

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[_LAYER_BASE] = LAYOUT_split_3x6_3(_LAYER_BASE_LEFT, _LAYER_BASE_RIGHT),
	[_LAYER_SYM] = LAYOUT_split_3x6_3(_LAYER_SYM_LEFT, _LAYER_SYM_RIGHT),
	[_LAYER_NUM] = LAYOUT_split_3x6_3(_LAYER_NUM_LEFT, _LAYER_NUM_RIGHT),
	[_LAYER_FUNC] = LAYOUT_split_3x6_3(_LAYER_FUNC_LEFT, _LAYER_FUNC_RIGHT),
	[_LAYER_MOUSE] = LAYOUT_split_3x6_3(_LAYER_MOUSE_LEFT, _LAYER_MOUSE_RIGHT),
	[_LAYER_COLEMAK] = LAYOUT_split_3x6_3(_LAYER_COLEMAK_LEFT, _LAYER_COLEMAK_RIGHT),
	[_LAYER_CUSTOM_LAYOUT] = LAYOUT_split_3x6_3(_LAYER_CUSTOM_LAYOUT_LEFT, _LAYER_CUSTOM_LAYOUT_RIGHT),
	[_LAYER_REVERSE_NUM] = LAYOUT_split_3x6_3(_LAYER_REVERSE_NUM_LEFT, _LAYER_REVERSE_NUM_RIGHT]),
	[_LAYER_REVERSE_BASE] = LAYOUT_split_3x6_3(_LAYER_REVERSE_BASE_LEFT, _LAYER_REVERSE_BASE_RIGHT)
};
